# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/approver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/approver.proto\x12\x08\x61pprover\x1a\x1egoogle/protobuf/wrappers.proto\"6\n\x08\x41pprover\x12*\n\x06status\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\"\"\n\x13ReadApproverRequest\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x05\"<\n\x14ReadApproverResponse\x12$\n\x08\x61pprover\x18\x01 \x01(\x0b\x32\x12.approver.Approver2`\n\x0f\x41pproverService\x12M\n\x0cReadApprover\x12\x1d.approver.ReadApproverRequest\x1a\x1e.approver.ReadApproverResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.approver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPROVER._serialized_start=67
  _APPROVER._serialized_end=121
  _READAPPROVERREQUEST._serialized_start=123
  _READAPPROVERREQUEST._serialized_end=157
  _READAPPROVERRESPONSE._serialized_start=159
  _READAPPROVERRESPONSE._serialized_end=219
  _APPROVERSERVICE._serialized_start=221
  _APPROVERSERVICE._serialized_end=317
# @@protoc_insertion_point(module_scope)
