# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import todo_pb2 as protos_dot_todo__pb2


class TodoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTodo = channel.unary_unary(
                '/todo.TodoService/CreateTodo',
                request_serializer=protos_dot_todo__pb2.CreateTodoRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.CreateTodoResponse.FromString,
                )
        self.ReadTodo = channel.unary_unary(
                '/todo.TodoService/ReadTodo',
                request_serializer=protos_dot_todo__pb2.ReadTodoRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.ReadTodoResponse.FromString,
                )
        self.UpdateTodo = channel.unary_unary(
                '/todo.TodoService/UpdateTodo',
                request_serializer=protos_dot_todo__pb2.UpdateTodoRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.UpdateTodoResponse.FromString,
                )
        self.DeleteTodo = channel.unary_unary(
                '/todo.TodoService/DeleteTodo',
                request_serializer=protos_dot_todo__pb2.DeleteTodoRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.DeleteTodoResponse.FromString,
                )
        self.ListTodos = channel.unary_unary(
                '/todo.TodoService/ListTodos',
                request_serializer=protos_dot_todo__pb2.ListTodosRequest.SerializeToString,
                response_deserializer=protos_dot_todo__pb2.ListTodosResponse.FromString,
                )


class TodoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTodo,
                    request_deserializer=protos_dot_todo__pb2.CreateTodoRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.CreateTodoResponse.SerializeToString,
            ),
            'ReadTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTodo,
                    request_deserializer=protos_dot_todo__pb2.ReadTodoRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.ReadTodoResponse.SerializeToString,
            ),
            'UpdateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTodo,
                    request_deserializer=protos_dot_todo__pb2.UpdateTodoRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.UpdateTodoResponse.SerializeToString,
            ),
            'DeleteTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTodo,
                    request_deserializer=protos_dot_todo__pb2.DeleteTodoRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.DeleteTodoResponse.SerializeToString,
            ),
            'ListTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTodos,
                    request_deserializer=protos_dot_todo__pb2.ListTodosRequest.FromString,
                    response_serializer=protos_dot_todo__pb2.ListTodosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todo.TodoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/CreateTodo',
            protos_dot_todo__pb2.CreateTodoRequest.SerializeToString,
            protos_dot_todo__pb2.CreateTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/ReadTodo',
            protos_dot_todo__pb2.ReadTodoRequest.SerializeToString,
            protos_dot_todo__pb2.ReadTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/UpdateTodo',
            protos_dot_todo__pb2.UpdateTodoRequest.SerializeToString,
            protos_dot_todo__pb2.UpdateTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/DeleteTodo',
            protos_dot_todo__pb2.DeleteTodoRequest.SerializeToString,
            protos_dot_todo__pb2.DeleteTodoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo.TodoService/ListTodos',
            protos_dot_todo__pb2.ListTodosRequest.SerializeToString,
            protos_dot_todo__pb2.ListTodosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
